version: "3.7"

networks:
  app-tier:
    driver: bridge

services:
  db:
    build:
      context: ./dockers/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kumparan
      MYSQL_USER: kumparan
      MYSQL_PASSWORD: kumparan
    ports:
      - "3306:3306"

  broker:
    container_name: broker
    build:
      context: dockers/broker
      dockerfile: Dockerfile
    hostname: broker-server
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - app-tier

  redis:
    build:
      context: dockers/cache
      dockerfile: Dockerfile
    container_name: kcache
    networks:
      - app-tier
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  es:
    build:
      context: dockers/es
      dockerfile: Dockerfile
    container_name: es
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    networks:
      - app-tier
    volumes:
      - es-data:/usr/share/elasticsearch/data

volumes:
  news-service:
  es-data:
    driver: local
  redis-data:
    driver: local